# Makefile for lab 6, part 2

CC = gcc

INCLUDES =
CFLAGS = -g -Wall $(INCLUDES)

LDDFLAGS = -g

http-client: 

.PHONY: clean
clean:
        rm -f *.o *~ a.out core http-client


.PHONY: all
all: clean http-client
~                                                                                                                                                                                              
~                                                                                                                                                                                              
~                                                    
