#Makefile lab 5 part1

CC = gcc

INCLUDES =
CFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = -g

.PHONY: test
test: mdb-lookup-server-nc-2 mdb-lookup-server-nc-1

mdb-lookup-server-nc-2.c: 

mdb-lookup-server-nc-1.c: 

.PHONY: clean
clean:
        rm -f *.o *~ a.out core mdb-lookup-server-nc-2 mdb-lookup-server-nc-1

.PHONY: all
all: clean
