#Makefile for lab 7, part 2

CC = gcc

INCLUDES =
CFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = -g

http-server:

.PHONY: clean
clean:
        rm -f *.o *~ a.out core http-server

.PHONY: all
all: clean http-server
~                                                                                                                                                                                            
~                                                                                                                                                                                            
~                                                                                                                                                                                            
~                                        
